#cloud-config

# Basic Ubuntu Server Setup Template
# This template provides a secure and well-configured Ubuntu server

package_update: true
package_upgrade: true
timezone: {{timezone}}

# Essential packages
packages:
  - curl
  - wget
  - ufw
  - fail2ban
  - htop
  - vim
  - git
  - unzip
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
{{packages}}

# Create users
users:
  - name: {{username}}
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - {{ssh_key}}

# Configure SSH
ssh_keys:
  rsa_private: |
    {{rsa_private_key}}
  rsa_public: |
    {{rsa_public_key}}

# Security configurations
write_files:
  # Configure fail2ban
  - path: /etc/fail2ban/jail.local
    permissions: '0644'
    owner: root:root
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 3
      
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3

  # Configure UFW rules
  - path: /etc/ufw/before.rules
    permissions: '0640'
    owner: root:root
    append: true
    content: |
      # Allow all on loopback
      -A ufw-before-input -i lo -j ACCEPT
      -A ufw-before-output -o lo -j ACCEPT

# System configurations
runcmd:
  # Configure firewall
  - ufw --force reset
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw --force enable
  
  # Start and enable fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Update system
  - apt update && apt upgrade -y
  
  # Clean up
  - apt autoremove -y
  - apt autoclean

# Configure automatic updates
package_update: true
package_upgrade: true
package_reboot_if_required: true

# Set locale
locale: en_US.UTF-8

# Configure NTP
ntp:
  enabled: true
  servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org

# Final message
final_message: |
  Ubuntu server setup complete!
  
  Default user: {{username}}
  SSH access configured with key authentication
  Firewall enabled (ports 22, 80, 443 open)
  Fail2ban enabled for SSH protection
  System updated and secured
  
  Connect via SSH: ssh {{username}}@<server-ip>
